# Generated by Django 5.2.10 on 2026-01-24 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="weight",
            field=models.FloatField(blank=True, null=True, verbose_name="Weight(Kg)"),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="workout.workout",
            ),
        ),
    ]
